### ISSUE TITLE
{'error': 'Unauthorized'}

### ISSUE THREAD

**Issue by joden95** [akasakaid/thetod#4]
![image](https://github.com/user-attachments/assets/1012be06-aed2-4839-a1c6-20257a73219e)

**Comment by FarmTon** [comment]
You must renew your tokens

**Comment by akasakaid** [comment]
> ![image](https://private-user-images.githubusercontent.com/159123995/350701445-1012be06-aed2-4839-a1c6-20257a73219e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDE0MzYsIm5iZiI6MTcyMTUwMTEzNiwicGF0aCI6Ii8xNTkxMjM5OTUvMzUwNzAxNDQ1LTEwMTJiZTA2LWFlZDItNDgzOS1hMWM2LTIwMjU3YTczMjE5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxODQ1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzk2ZjZiMzkwMzEyNDVhOTZlNGNiY2I3YzZhMTUzZDQyNDA5ZmI4Zjk1ZDVmODVjNjNjMDI0MmY0MzhiNWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D7a1aAszDRTd-oxWQgF-3uqv77gkzc-PXkwN21egKKU)

Yeah, you have to get a new query (user=), because the query data will expire in 24 hours.

**Comment by joden95** [comment]
Thanks, I didn't know this. I found everything, fixed everything and now everything works. You can close the issue
